import Link from 'next/link'

const sections = [
  ['What to Discuss Before Booking Court Marriage in Lahore',
    'Start your enquiry with the information that affects the proposed arrangements: where both partners live, your preferred date, your current identity documents and whether either person has previously been married. Mention any legal question, missing record or travel deadline at the beginning. An initial discussion should help you understand what needs review before an appointment can be confirmed. Ask which parts of the service concern nikah preparation, which concern registration and which would require separate professional advice.',
    'Make a short list of questions that both partners want answered. Include the venue, attendance, witnesses, document copies and the records you expect to receive. Before making travel plans, confirm who will coordinate the appointment and how you will be notified if preparation is incomplete. Keep the agreed checklist in one place so that neither partner is relying on a different understanding of the arrangements.'],
  ['Preparing Identity Documents and Supporting Records',
    'Check the names, identification numbers and other personal details on the documents you intend to use. If a name is spelled differently across records, explain the difference during review instead of waiting until the Nikah Nama is being completed. Ask which identity originals must be available, which copies should be prepared and whether additional age or nationality evidence is needed. If a document has expired or is unavailable, discuss the acceptable next step before committing to an appointment.',
    'For a previous marriage, identify the relevant divorce or deceased spouse’s death records and have their suitability reviewed. Do not assume that an informal statement is enough to resolve a question about marital status. Foreign nationality, overseas residence or representation can require a different document review. Photographs, translations, affidavits and other supporting paperwork should be confirmed for your circumstances rather than treated as a universal list for every couple.'],
  ['Understanding the Nikah Nama Before Signing',
    'The Nikah Nama deserves careful attention because it records personal details and the terms of the marriage. Both partners should understand the entries, including the agreed Haq Mehr and how its payment is described. Ask for an explanation of any field you do not understand. Review names, identity details, dates and witness information before signing, and raise corrections while the document is being prepared. Allow time for this review when planning your appointment.',
    'If you wish to discuss particular marriage conditions, raise them before the ceremony and seek appropriate advice on how they should be recorded. Avoid leaving decisions about important terms to the final moment. Clarify which completed copies will be provided and how they relate to registration follow up. Keep readable copies of your records securely so that a later certificate enquiry can begin with accurate information.'],
  ['Planning Witnesses and Attendance in Lahore',
    'Confirm the applicable witness requirements with the person conducting the nikah and establish who will attend. Ask which witness identification details need to be available for paperwork. If you need assistance discussing witness arrangements, include this in the initial enquiry rather than assuming that it is part of every service. Both partners should also know the appointment location and the participation expected of them before the day arrives.',
    'For couples travelling into Lahore, allow for the practical work needed before the ceremony: checking originals, reviewing the document and confirming the recorded terms. If either person cannot attend as proposed, explain that early so the arrangement can be reviewed. Explore online nikah separately if distance affects your plans. Remote participation and the acceptance of resulting documents need individual consideration, particularly where another country’s authority will later review them.'],
  ['Marriage Registration and Certificate Follow Up',
    'Ask how your marriage registration will be coordinated and which relevant office will hold the record. Establish who is responsible for follow up, what information they need and how you will receive an update. The nikah appointment, registration and a subsequent certificate request are different stages of planning; clarify their relationship before booking. If you need the records by a particular date, mention that requirement when discussing the service scope.',
    'For a marriage certificate enquiry, explain why the document is needed and share the receiving organisation’s checklist. Confirm whether certificate assistance is included in your quote or requires a separate request. Ask how you will receive documents if you live outside Lahore, whether delivery is available and which originals must be retained. If a recorded detail needs correction, discuss the appropriate official process rather than altering a copy yourself.'],
  ['Comparing Court Marriage Fees in Lahore',
    'When comparing quotes, look at what each service includes. Ask whether the amount covers document preparation, nikah coordination and registration follow up, and which official or optional charges are separate. Certificate assistance, translation, delivery or additional legal work may need separate discussion. A clear quote should let you identify the agreed tasks and understand what would change the cost if your requirements develop.',
    'Before paying, confirm the recipient, the service being booked and how payment will be acknowledged. Ask about the arrangements if an appointment needs to move because documents are incomplete or circumstances change. Keep the written scope alongside your document checklist. The aim is to make a decision based on the actual service you need, with a clear understanding of costs and outstanding requirements before you proceed.'],
  ['Court Marriage Enquiries from Overseas Pakistanis',
    'If you are overseas and planning to marry in Lahore, explain whether you intend to travel or need to explore participation from abroad. Include the location and nationality of both partners, your travel window and the purpose for which you will use the marriage records. These details help focus the discussion on preparation and the arrangements that need review. Do not assume that a local appointment plan automatically covers remote participation.',
    'For documents intended for an overseas application, start with the receiving authority’s current instructions. Ask what type of marriage record is requested and whether translation, attestation or additional verification is needed. Acceptance is determined by the organisation receiving the documents, so its checklist should guide your preparation. Keep document delivery and any further review time in your schedule alongside the proposed nikah date.'],
  ['Your Final Appointment Checklist',
    'Before attending, check that both partners understand the venue, time, agreed service and documents to bring. Confirm witness participation, outstanding paperwork and the marriage terms to be recorded. Ask who to contact if a preparation question remains unresolved. A final review of these practical details makes it easier to arrive with the information needed, rather than discover an avoidable gap at the appointment.',
    'Keep a separate list for the work that follows the ceremony: registration updates, the copies to receive and any certificate or overseas documentation requests. Agree how you will be contacted about those stages. If your plans involve another city as well as Lahore, explain the connection so the actual place of marriage and relevant registration arrangements remain clear throughout the discussion.'],
]

export default function LahoreCourtGuide() {
  return <section className="lahore-court-guide" aria-labelledby="lahore-guide-title"><h2 id="lahore-guide-title">Planning Your Court Marriage in Lahore</h2><p>Use this detailed guide alongside your confirmed requirements checklist to prepare questions, organise documents and understand the service you are booking.</p><div className="guide-content">{sections.map(([title, ...paragraphs]) => <article key={title}><h3>{title}</h3>{paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</article>)}</div><div className="guide-links"><Link href="/online-nikah">Online Nikah for Overseas Pakistanis<span aria-hidden="true">↗</span></Link><Link href="/marriage-certificate">Marriage Certificate Assistance<span aria-hidden="true">↗</span></Link><a href="#contact">Discuss Your Lahore Appointment<span aria-hidden="true">↗</span></a></div></section>
}
