import Link from 'next/link'
import SiteNav from '../../components/site-nav'
import HappyClients from '../../components/happy-clients'
import SiteFooter from '../../components/site-footer'
import { JsonLd, breadcrumbSchema } from '../../components/json-ld'
import { pageMetadata } from '../../lib/seo'
import { ArrowUpRight, Check, Globe2, FileText, HeartHandshake } from 'lucide-react'

export const metadata = pageMetadata({
  title: 'About Us – Court Marriage & Online Nikah Support',
  description: 'About NikahRegister: court marriage in Karachi, Lahore, Islamabad and Rawalpindi, online nikah for overseas Pakistanis and NADRA marriage certificate support.',
  path: '/about-us',
})

const services = [
  ['01', 'Court Marriage', 'Discuss document preparation, nikah arrangements and registration questions before choosing an appointment in your preferred city.', '/court-marriage'],
  ['02', 'Online Nikah', 'Start a focused enquiry about participation, scheduling and documentation when partners are in different cities or countries.', '/online-nikah'],
  ['03', 'Marriage Certificate', 'Understand the records requested for your purpose and the next steps for a new certificate or existing marriage documentation enquiry.', '/marriage-certificate'],
]

export default function AboutUsPage() {
  return <div className="site-shell"><JsonLd data={breadcrumbSchema([['Home', '/'], ['About Us', '/about-us']])} /><SiteNav /><main>
    <section className="hero section-pad about-page-hero"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">About NikahRegister</p><h1>A Clearer Beginning.<br /><em>A Considered Approach.</em></h1><h2 className="about-page-subheading">Marriage Services &amp; Documentation Support for Pakistan and Overseas</h2><p className="hero-text">NikahRegister gives couples and families a clear starting point for court marriage, online nikah and marriage certificate enquiries. We bring practical questions about preparation, participation and records into one conversation, so you can understand the proposed arrangements before taking your next step.</p><div className="hero-actions"><Link className="button button-primary" href="/#contact">Talk to Us <ArrowUpRight size={17} /></Link><a className="text-link" href="#about-services">Explore Our Services <span aria-hidden="true">↗</span></a></div><div className="trust-line"><Check size={14} /> Thoughtful <i>•</i> Clear <i>•</i> Personal</div></div><div className="hero-visual"><div className="hero-main-image"><img src="/images/ceremony.webp" width="1200" height="655" fetchPriority="high" alt="Ivory nikah ceremony setting with elegant wedding details" /></div><div className="hero-thumbs"><img src="/images/nikah-signing-ivory-thumb.webp" width="320" height="320" loading="lazy" alt="Nikah document preparation and signing details" /><img src="/images/wedding-details-ivory-thumb.webp" width="320" height="320" loading="lazy" alt="Ivory wedding arrangement" /></div></div></div></section>
    <section className="section-pad about-section"><div className="about-grid"><div className="about-image"><img src="/images/couple-portrait.webp" width="1200" height="655" loading="lazy" alt="Couple preparing for a new chapter together" /><div className="image-caption">An important decision deserves careful preparation.</div></div><div className="about-copy"><p className="eyebrow">Who we are</p><h2>Practical Support.<br /><em>Personal Attention.</em></h2><p className="intro-text">Marriage planning often begins with questions: which documents should you prepare, where should you proceed and what records will you need afterwards? NikahRegister is built around making those questions easier to discuss.</p><p className="intro-text about-page-paragraph">Our website helps you find the service and location connected to your enquiry. From there, explain your circumstances, preferred timing and documentation needs so that the proposed service can be discussed with a clear scope. We encourage both partners to understand the arrangements, the agreed terms and the steps requiring further confirmation.</p></div></div></section>
    <section className="section-pad services-section" id="about-services"><div className="section-intro"><p className="eyebrow">How we can help</p><h2>Support for Your Marriage Journey</h2><p className="intro-text">Choose the service that matches your situation, whether you are planning a new marriage or seeking records for an existing one.</p></div><div className="service-grid about-service-grid">{services.map(([number, title, text, href]) => <article className="service-card" key={href}><div className="card-top"><span>{number}</span><ArrowUpRight size={21} strokeWidth={1.4} /></div><h3>{title}</h3><p>{text}</p><Link href={href}>Explore {title} <ArrowUpRight size={16} /></Link></article>)}</div></section>
    <section className="section-pad about-values"><div className="section-intro"><p className="eyebrow">Our approach</p><h2>Clarity at Every Conversation</h2><p className="intro-text">A useful enquiry should help you understand what to prepare, what to confirm and what comes next.</p></div><div className="karachi-preparation">{[
      [HeartHandshake, 'Listen to Your Circumstances', 'We start with the location of both partners, your preferred timing and the purpose of your enquiry. Share any travel, previous marriage or documentation issue early so that the conversation reflects your actual situation.'],
      [FileText, 'Explain the Practical Details', 'Discuss identity records, agreed marriage terms, participation and the documents you expect to receive. Ask for a clear checklist and service scope before committing to arrangements or paying for additional work.'],
      [Globe2, 'Plan Beyond the Appointment', 'Registration, certificate requests and overseas document use may involve separate steps. Identify the receiving authority and confirm its requirements so that your planning covers the records you need after the ceremony.'],
    ].map(([Icon, title, text]) => <article key={title}><Icon size={23} strokeWidth={1.4} className="about-value-icon" /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <HappyClients />
    <section className="locations-section"><div className="location-inner"><div className="section-intro"><p className="eyebrow">Pakistan &amp; overseas</p><h2>Connected Across Locations</h2><p className="intro-text">Explore court marriage enquiries for Karachi, Lahore, Islamabad and Rawalpindi, or start an online nikah enquiry from Pakistan and overseas.</p></div><div className="locations-grid">{['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi'].map((city, index) => <Link className="location-card" key={city} href={`/court-marriage/${city.toLowerCase()}`}><span>0{index + 1}</span>{city}<ArrowUpRight size={15} /></Link>)}</div><p className="about-overseas-copy">For overseas enquiries, our Online Nikah pages cover the UAE, UK, USA, Canada, Saudi Arabia, Australia, Oman and Qatar. Tell us where you and your partner are located and where the marriage records will be used. Remote participation, signing and document acceptance need confirmation for the proposed arrangement.</p><Link className="about-overseas-link" href="/online-nikah">Explore Online Nikah Country Pages <ArrowUpRight size={16} /></Link></div></section>
    <section className="section-pad"><div className="faq-grid"><div className="section-intro"><p className="eyebrow">Before you begin</p><h2>Your Questions.<br /><em>A Clear Next Step.</em></h2></div><div className="about-next-copy"><p>Start by telling us the service you need, the city or country connected to your plans and any deadline. You do not need to send every document in your first message. Ask which information is needed and how the proposed service will be coordinated.</p><p>Confirm the agreed scope, fee and appointment arrangements before proceeding. Where your circumstances require individual legal advice or official confirmation, make that part of the preparation discussion.</p><Link href="/#contact" className="button button-primary">Discuss Your Requirements <ArrowUpRight size={17} /></Link></div></div></section>
  </main><SiteFooter /></div>
}
